language: ruby
bundler_args: --without debug
script: "bundle exec rspec spec"
env:
  - CI=true
rvm:
  - 2.2.4
  - 2.3.0
  - jruby
cache: bundler
sudo: false
matrix:
  allow_failures:
    - rvm: jruby
